### ISSUE TITLE
DPF - Equality Check

### ISSUE THREAD

**Issue by ShokofehVS** [nann-cheng/PDTE#1]
Hi @nann-cheng 

I recently found the paper associated with this project quite interesting and helpful for my implementation on equality check itself. However, it is hard in the code to distinguish how DPF based on Sycret is working. 

I imagined these parts importantly can point me to just have equality check: 
`dealer.py: def distributeCmpKeys`
`player.py: def compare0`
and `server.py` on distribution of FSS keys to player

I would appreciate it if you could help me the code be clearer in terms of implementation of equality check.

**Comment by nann-cheng** [comment]
Thanks for your question. But it's unrelated with this project, since it uses only LessThan Check, actually you can find good examples using equality check from sycret here 

https://github.com/OpenMined/sycret/blob/master/test/test_eq.py

**Comment by nann-cheng** [comment]
Thanks for your question. Yes, you are right. In server.py, it's used to run the program which calls corresponding snippet from all other *.py files (dealer.py, player.py, ...). Regarding DPF based equlity check, keys are generated in ''dealer.py: def distributeCmpKeys'', evaluated in "player.py: def compare1".

![Xnip2024-09-25_23-04-48](https://github.com/user-attachments/assets/9dd2d1c1-93da-48e0-85d6-650bc381de67)

**Comment by ShokofehVS** [comment]
Thanks for your response. I have made it work. 
Your project seems very promising, keep up you great work @nann-cheng.
